development: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'cf663ea0a8f69805ebeec6769545247699a8731a0ff349e4303ce7fb5b50a11cfde5bce599c93562f57f41c44a1c9fd42325ecaf5bc4d75effea8d8db8dfe152' %>



test: *default
production: *default
webapp: *default
webapp-af: *default
stage: *default